version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: clean-css
    versions:
    - 5.0.1
    - 5.1.0
    - 5.1.1
